In [ ]:
import numpy as np

In [ ]:
import scipy

In [3]:
a = [1,2,3]

In [4]:
type(a)

list

In [8]:
np.array(a)

array([1, 2, 3])

In [9]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [10]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [11]:
arr.max()

95

In [12]:
arr.argmax()

0

In [13]:
arr.argmin()

7

In [14]:
 arr.mean()

60.8

In [16]:
arr.shape

(10,)

In [18]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [21]:
mat = np.arange(0,100).reshape(10,10)

In [22]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
mat[0,1]

1

In [ ]:
mat[:3,:3]

In [ ]:
import numpy as np

In [25]:
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from PIL import image

ImportError: cannot import name 'image' from 'PIL' (/home/kumar/anaconda3/lib/python3.7/site-packages/PIL/__init__.py)